### ISSUE TITLE
One potential risk found in the function Hardware::validateResponse in the file Hardware.cpp

### ISSUE THREAD

**Issue by betamoojw** [OpenKNX/OGM-Common#3]
Thank you guys for creating and continuing contributing the outstanding OpenKNX repos.  It does give me the chance to learn about the details behind KNX device (hardware and software). Hopefully I could make some contributions here.

After reviewing, there is one potential risk found in the function Hardware::validateResponse in the file OGM-Common\src\OpenKNX\Hardware.cpp in the branch modular. This potential risk may result in the false validation response. It will be great if you could consider to correct it. 
![image](https://user-images.githubusercontent.com/40590760/220813625-37161e63-8d3c-4e16-a838-3d841a2d341b.png)

**Comment by traxanos** [comment]
Thanks for finding it. The test was originally limited to only one character. The for loop came around later. I have just fixed the error.
