### ISSUE TITLE
add loop time statistics

### ISSUE THREAD

**Issue by Ing-Dom** [OpenKNX/OGM-Common#9]
gather statistics for the loop time - average, min, max, % and/or cnt that exceed some level, etc. pp.
maybe do that per module or at least seperate for knx stack ?

**Comment by mumpf** [comment]
I agree, knx-stack should be measured seperately. And I would favour stats per module. Otherwise nobody knows, how to interpret "loop took too long" message.

**Comment by cornelius-koepp** [comment]
> gather statistics for the loop time 
- [x] runtime
- [x] waitingtime between runs

> average, min, max, % and/or cnt that exceed some level
- [x] average
- [x] min
- [x] max
- [x] histogram
- [x] median (estimation)
- [x] sum
- [x] counter

> per module or at least seperate for knx stack
- [x] core0
  - [x] per module
  - [x] modules loop
  - [x] stack
  - [x] commons loop
- [ ] core1 (will not affect knx-stack in v1)
  - [ ] modules loop
